//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otter.Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Color")]
        public global::Otter.Editor.BackgroundMode ViewBackgroundMode {
            get {
                return ((global::Otter.Editor.BackgroundMode)(this["ViewBackgroundMode"]));
            }
            set {
                this["ViewBackgroundMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ViewBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["ViewBackgroundColor"]));
            }
            set {
                this["ViewBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Otter.Editor.img.view_background.png")]
        public string ViewBackgroundImage {
            get {
                return ((string)(this["ViewBackgroundImage"]));
            }
            set {
                this["ViewBackgroundImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentProjects {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentProjects"]));
            }
            set {
                this["RecentProjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWelcome {
            get {
                return ((bool)(this["ShowWelcome"]));
            }
            set {
                this["ShowWelcome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AliceBlue")]
        public global::System.Drawing.Color ViewSelectColor {
            get {
                return ((global::System.Drawing.Color)(this["ViewSelectColor"]));
            }
            set {
                this["ViewSelectColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SteelBlue")]
        public global::System.Drawing.Color ViewInnerSelectColor {
            get {
                return ((global::System.Drawing.Color)(this["ViewInnerSelectColor"]));
            }
            set {
                this["ViewInnerSelectColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int ViewGridIncrement {
            get {
                return ((int)(this["ViewGridIncrement"]));
            }
            set {
                this["ViewGridIncrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ViewSnapTolerance {
            get {
                return ((int)(this["ViewSnapTolerance"]));
            }
            set {
                this["ViewSnapTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color ViewBoundsColor {
            get {
                return ((global::System.Drawing.Color)(this["ViewBoundsColor"]));
            }
            set {
                this["ViewBoundsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveOnExport {
            get {
                return ((bool)(this["SaveOnExport"]));
            }
            set {
                this["SaveOnExport"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.otterui.com/otterui/help-1.3.6.3")]
        public string HelpURL {
            get {
                return ((string)(this["HelpURL"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoKeyFrame {
            get {
                return ((bool)(this["AutoKeyFrame"]));
            }
            set {
                this["AutoKeyFrame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::Otter.UI.AnchorFlags AnchorFlags {
            get {
                return ((global::Otter.UI.AnchorFlags)(this["AnchorFlags"]));
            }
            set {
                this["AnchorFlags"] = value;
            }
        }
    }
}
